### PR TITLE
Support folder tags

### PR DESCRIPTION
**Pull request by ikesau**
Hey @erikelisath

Because I've started using nextcloud, which categorizes its notes based on subfolders, I wanted to modify this script to support that.

Let me know if you'd like this feature merged in, and I'll tidy up the code and document it. (I also added some "test data" to make it easier to validate.)

Business logic:
1. Check if `folders` argument is passed to the script
2. Per each note, grab the first label assigned to it and created a nested folder within the `notes` output folder
3. Create a nested `resources` folder in each subfolder
4. Store each note in the nested folder

### CODE REVIEW

**Comment by erikelisath** [comment]
Hey @ikesau 
thank you for your feature request. I will check it up and give feedback for a possible merge!

**Comment by erikelisath** [comment]
Your code will not work with the default call `python keep-to-markdown.py path/to/folder`, it will end with _Please enter a correct path!_. But if you add the parameter `folders` it will run correctly. 

Let me build in new command line arguments, like `python keep-to-markdown.py -i path/to/folder -t` with `-i` as input path and `-t` as categorize folder by tags. So everyone has the the option to categorize the folder by tags or not.

**Comment by erikelisath** [comment]
Added the new command line arguments:
```
> python keep-to-markdown.py -h
usage: keep-to-markdown.py [-h] -i PATH [-t]

Converting Google Keep notes to markdown files.

optional arguments:
  -h, --help  show this help message and exit
  -i PATH     path to the Takout folder
  -t          create and categorized folders by tags
```
and I have adapted your code to read it better.

Please test it with your Keep notes. It still works with your testdata.

**Comment by ikesau** [comment]
Thank you for that! 

I've rewritten the README to explain the new feature and improve clarity. 👍

**Comment by erikelisath** [comment]
Thank you for fixing the typo and improving the readme! 
It can be easily merged now.

**Pull request merged**
